# traefik.toml
logLevel = "DEBUG"
accessLogsFile="log/access.log"

defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":8085"
[web]

[file]

# rules
[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://127.0.0.1:8123"
 
[frontends]
  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.routes.test_1]
    rule = "Host:ha.office.talpau"
  [frontends.tixu1]
  backend = "backend1"
    [frontends.tixu1.routes.tixu_1]
    rule = "Host:ha.tixu.be"
